### PR TITLE
BEQS Empty column fix - Closes #99

### LINKED ISSUE #99: BEQS - Empty columns
The BEQS function fails under the following two circumstances:
 * When the first 25 rows of the returned data is NA
 * When the entire column returned is NA

### PR DESCRIPTION
**Pull request by csrvermaak**

### CODE REVIEW

File: src/beqs.cpp [hunk 1]
```diff
@@ -107,6 +109,20 @@ Rcpp::DataFrame processResponseEvent(Event event, const bool verbose) {
...
+
+        if(all_chk){
+            break;
+        }
+    }
+
+    if(!all_chk){               // Check if any columns have not been checked successfully - these will all set to fallback NA
+        for (int i=0; i<cols; i++) {
+            if(!chk[i]){
+                lst[i] = Rcpp::CharacterVector(rows, R_NaString);
```
Comment (eddelbuettel) [inline src/beqs.cpp]: That doesn't work. 

We may be one of four types here. You are assuming it is always character when it might be numeric or date or ... and you cannot assign a character-NA to these others.

We might be able to assign `R_NilValue`.

Comment (csrvermaak) [inline src/beqs.cpp]: 100%  - happy to append. What class should it be: RawVector or GenericVector?

Comment (eddelbuettel) [inline src/beqs.cpp]: I spoke to soon.  Your logic is to fill the entire column _j_ if it was never set?

Comment (csrvermaak) [inline src/beqs.cpp]: Yes, the logic is: search for a type until found, then stop searching.

If no type found, there was no value in the column, thus entire column is NA.

Comment (eddelbuettel) [inline src/beqs.cpp]: Which even I understood once I got to the third cup'o'joe  ;-)

Thanks for the enhancement!
